on: [push]
name: Azure ARM
jobs:
  provision:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az deployment sub create --location southafricanorth --template-file ./template/main.bicep
  
  deploy:
    runs-on: ubuntu-latest
    needs: provision
    steps:
      - uses: actions/checkout@v3
      
      - name: dotnet publish
        run: dotnet publish
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with: 
          app-name: mosvcapp #${{ needs.provision.outputs.appServiceName }} 
          #package: .publish/myApp
